"""Dev-time harvester: poedb Divination_Cards -> cited metadata file (ADR-0006).

    uv run python tools/harvest_divination_cards.py --league Standard

Outside the `oracle` package on purpose: not shipped, not in the runtime HTTP allowlist,
not compliance-scanned. Writes a cited, versioned data file; cross-checks card names
against the live poe.ninja DivinationCard feed (informational only — recipe facts are
independent of pricing, ADR-0002).
"""

from __future__ import annotations

import argparse
import hashlib
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

import httpx
import yaml

from oracle.metadata.divination_cards import parse_divination_cards_html

POEDB_URL = "https://poedb.tw/us/Divination_Cards"
NINJA_URL = "https://poe.ninja/poe1/api/economy/exchange/current/overview"
UA = "oracle-dev-harvest (personal PoE tool; contact via repo)"
OUT_PATH = Path("data/metadata/divination_cards.yaml")


def _fetch_page() -> bytes:
    resp = httpx.get(POEDB_URL, headers={"User-Agent": UA}, timeout=30.0)
    resp.raise_for_status()
    return resp.content


def _ninja_card_names(league: str) -> set[str]:
    resp = httpx.get(
        NINJA_URL,
        params={"league": league, "type": "DivinationCard"},
        headers={"User-Agent": UA},
        timeout=30.0,
    )
    resp.raise_for_status()
    return {i["name"] for i in resp.json().get("items", []) if "name" in i}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--league", required=True, help="league to cross-check card coverage")
    args = parser.parse_args()

    page = _fetch_page()
    cards = parse_divination_cards_html(page.decode("utf-8"))
    if not cards:
        raise SystemExit("parsed 0 cards — poedb markup likely changed (fail loud)")

    doc = {
        "source": {
            "url": POEDB_URL,
            "fetched_at": datetime.now(tz=UTC).date().isoformat(),
            "page_sha256": hashlib.sha256(page).hexdigest(),
        },
        "cards": [
            {
                "name": c.name,
                "set_size": c.set_size,
                "reward_name": c.reward_name,
                "reward_qty": c.reward_qty,
                "reward_kind": c.reward_kind,
            }
            for c in sorted(cards, key=lambda c: c.name)
        ],
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as fh:
        fh.write("# GENERATED by tools/harvest_divination_cards.py — do not edit by hand.\n")
        fh.write("# Source of truth: poedb (ADR-0001, ADR-0006). Re-harvest on patch day.\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True)

    kinds = Counter(c.reward_kind for c in cards)
    priceable = _ninja_card_names(args.league)
    card_covered = sum(1 for c in cards if c.name in priceable)
    print(f"wrote {len(cards)} cards to {OUT_PATH}")
    print(f"reward kinds: {dict(kinds)}")
    print(f"card leg priced on DivinationCard feed: {card_covered}/{len(cards)}")


if __name__ == "__main__":
    main()
