"""Dev-time harvester: poedb Vendor_recipe_system -> cited metadata file.

Run on patch day (or when the recipe set changes):

    uv run python tools/harvest_vendor_recipes.py --league Standard

This lives OUTSIDE the `oracle` package on purpose: it is not shipped, not part of the
runtime HTTP allowlist, and not scanned by the compliance test. It is the only code that
talks to poedb, and it does so once, writing a cited, versioned data file (ADR-0001).
It also cross-checks recipe item names against the live poe.ninja Currency feed and
prints a coverage report, but does NOT filter the file by coverage — recipe facts are
independent of pricing (ADR-0002).
"""

from __future__ import annotations

import argparse
import hashlib
from datetime import UTC, datetime
from pathlib import Path

import httpx
import yaml

from oracle.metadata.vendor_recipes import parse_vendor_recipes_html

POEDB_URL = "https://poedb.tw/us/Vendor_recipe_system"
NINJA_CURRENCY_URL = "https://poe.ninja/poe1/api/economy/exchange/current/overview"
UA = "oracle-dev-harvest (personal PoE tool; contact via repo)"
OUT_PATH = Path("data/metadata/vendor_recipes.yaml")


def _fetch_page() -> bytes:
    resp = httpx.get(POEDB_URL, headers={"User-Agent": UA}, timeout=30.0)
    resp.raise_for_status()
    return resp.content


def _ninja_currency_keys(league: str) -> set[str]:
    resp = httpx.get(
        NINJA_CURRENCY_URL,
        params={"league": league, "type": "Currency"},
        headers={"User-Agent": UA},
        timeout=30.0,
    )
    resp.raise_for_status()
    payload = resp.json()
    return {item["name"] for item in payload.get("items", []) if "name" in item}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--league",
        required=True,
        help="league to cross-check name coverage against (e.g. the permanent one)",
    )
    args = parser.parse_args()

    page = _fetch_page()
    page_sha = hashlib.sha256(page).hexdigest()
    recipes = parse_vendor_recipes_html(page.decode("utf-8"))
    if not recipes:
        raise SystemExit("parsed 0 vendor recipes — poedb markup likely changed (fail loud)")

    doc = {
        "source": {
            "url": POEDB_URL,
            "fetched_at": datetime.now(tz=UTC).date().isoformat(),
            "page_sha256": page_sha,
        },
        "recipes": [
            {
                "id": r.id,
                "output": {"name": r.output.name, "qty": r.output.qty},
                "inputs": [{"name": i.name, "qty": i.qty} for i in r.inputs],
                "npc": r.npc,
            }
            for r in sorted(recipes, key=lambda r: r.id)
        ],
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as fh:
        fh.write("# GENERATED by tools/harvest_vendor_recipes.py — do not edit by hand.\n")
        fh.write("# Source of truth: poedb (ADR-0001). Re-harvest on patch day.\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True)

    # Coverage report (informational; file is NOT filtered by it).
    keys = _ninja_currency_keys(args.league)
    names = {i.name for r in recipes for i in [*r.inputs, r.output]}
    missing = sorted(n for n in names if n not in keys)
    covered = len(names) - len(missing)
    print(f"wrote {len(recipes)} recipes to {OUT_PATH}")
    print(f"ninja Currency coverage: {covered}/{len(names)} item names matched")
    if missing:
        print("  names NOT in the live Currency feed (will price as missing):")
        for n in missing:
            print(f"    - {n}")


if __name__ == "__main__":
    main()
